tag-template: 'v$RESOLVED_VERSION'
template: |
  ## :eyes: What's new
  $CHANGES

  **Full Changelog**: https://github.com/czernika/tailwind-grid-area/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
change-template: '- $TITLE ([#$NUMBER](https://github.com/czernika/tailwind-grid-area/pull/$NUMBER)) by @$AUTHOR'
no-changes-template: '* Minor changes'

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feat'
  default: patch