name: Publish Release

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present
      
      - name: Run Tests
        run: npm test

      # # Check remote and local version of package
      # - name: Read package.json Version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@main

      # - name: Get Package Version from NPM Registry
      #   id: registry-version
      #   run: |
      #     echo "NPM_PACKAGE_VERSION=$(npm view tailwindcss-grid-area version)" >> $GITHUB_ENV

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.name }}

      - name: Commit Updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update version and CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: 'CHANGELOG.md package.json'
      
      - name: Publish Release on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.run_id }} - Failed Release Pipeline! ${{ github.actor }} with commit:
            ${{ github.event.commits[0].message }}