name: Create Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # PR based Release Drafter
      - name: Generate CalVer version
        id: calver
        run: |
          export VERSION=$(date "+%Y.%m.%d")
          echo ::set-output name=version::${VERSION}
          echo "Version set to ${VERSION}"

      - uses: release-drafter/release-drafter@v5
        id: release
        with:
          name: Release ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Conventional Commit based Release Drafter
      # - name: Get Next Semantic Version
      #   id: semver
      #   uses: ietf-tools/semver-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master

      # - name: Get List of Changes
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref_name }}

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true
      #     draft: true
      #     sinceTag: ${{ steps.semver.outputs.current }}
      #     name: ${{ steps.semver.outputs.next }}
      #     tag: ${{ steps.semver.outputs.next }}
      #     body: |
      #       ## What's Changed :eyes:
      
      #        ${{ steps.changelog.outputs.changelog }}
      
      #        **Full Changelog**: https://github.com/czernika/tailwind-grid-area/compare//${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}
      #     token: ${{ secrets.GITHUB_TOKEN }}