name: Create Release Draft

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Read package.json Version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@main

      # - name: Get Package Version from NPM Registry
      #   id: registry-version
      #   run: |
      #     echo "NPM_PACKAGE_VERSION=$(npm view tailwindcss-grid-area version)" >> $GITHUB_ENV

      # - name: Send Telegram Notification
      #   uses: appleboy/telegram-action@master
      #   if: ${{ steps.package-version.outputs.current-version }} == ${{ env.NPM_PACKAGE_VERSION }}"
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     message: |
      #       TailwindCSS Grid Area package requires to bump version manually

      - name: Get Next Semantic Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.semver.outputs.current }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: |
            ## What's Changed :eyes:

            ${{ steps.changelog.outputs.changes }}

            **Full Changelog**: https://github.com/czernika/tailwindcss-grid-area/compare//${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.run_id }} - Failed Draft Release Pipeline! ${{ github.actor }} with commit:
            ${{ github.event.commits[0].message }}